<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.bienvenu</groupId>
    <artifactId>bienvenu</artifactId>
    <version>0.0.1</version>
  </parent>
  <artifactId>bienvenuEar</artifactId>
  <packaging>ear</packaging>
  <name>BienvenuEar</name>
  
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
        <!-- EJB Module -->
        <dependency>
            <groupId>com.bienvenu</groupId>
            <artifactId>bienvenuEJB</artifactId>
            <version>0.0.1</version>
            <type>ejb</type>
        </dependency>

        <!-- Web Module -->
        <dependency>
            <groupId>com.bienvenu</groupId>
            <artifactId>bienvenuWeb</artifactId>
            <version>0.0.1</version>
            <type>war</type>
        </dependency>

        <!-- Auth Module -->
        <dependency>
            <groupId>com.bienvenu</groupId>
            <artifactId>bienvenuAuthEJB</artifactId>
            <version>0.0.1</version>
            <type>ejb</type>
        </dependency> 
        
        <!-- API Web Module -->
        <dependency>
           <groupId>com.bienvenu</groupId>
           <artifactId>bienvenuApiWEB</artifactId>
           <version>0.0.1</version>
           <type>war</type>
           </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ear-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <defaultLibBundleDir>lib</defaultLibBundleDir>
                    <modules>
                        <webModule>
                            <groupId>com.bienvenu</groupId>
                            <artifactId>bienvenuWeb</artifactId>
                            <contextRoot>/</contextRoot>
                        </webModule>
                        <webModule>
                            <groupId>com.bienvenu</groupId>
                            <artifactId>bienvenuApiWEB</artifactId>
                            <contextRoot>/api</contextRoot> <!-- ✅ -->
                        </webModule>
                        <ejbModule>
                            <groupId>com.bienvenu</groupId>
                            <artifactId>bienvenuEJB</artifactId>
                        </ejbModule>
                        <ejbModule>
                            <groupId>com.bienvenu</groupId>
                            <artifactId>bienvenuAuthEJB</artifactId>
                        </ejbModule>
                    </modules>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>